name: Java CD Actions

on:
  workflow_run:
    workflows: ["Java CI Action"]
    types:
      - completed

jobs:
  deploy: 
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v5
        with: 
          name: my-app-artifact
    
      - name: Login toDocker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push
        uses: docker/build-push-action@v6
        with: 
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-java-app:latest

