name: Java CD Action

on:
  workflow_run:
    workflows: ["Java CI Action"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy: 
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Pull image 
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-java-app:latest
      
      - name: Run Container
        run: docker run -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/my-java-app:latest
        