name: Java CI Action
on:
  push:
      branches: [ "main" ]
  pull_request:
      branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.7.1
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x ./app/gradlew
        
      - name: Run tests with Gradle
        working-directory: ./app
        run: ./gradlew test
        
      - name: Build and analyze with SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: ./app
        run: ./gradlew build sonar --info
      
      - name: Login toDocker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and Push
        uses: docker/build-push-action@v6
        with: 
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-java-app:latest

