name: Java CI Action
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Setup Java JDK
            uses: actions/setup-java@v4.7.1
            with:
              java-version: '21'
              distribution: 'temurin'
              cache: 'gradle'

          - name: Grant execute permission for gradlew
            run: chmod +x ./app/gradlew

          - name: Setup Gradle
            uses: gradle/actions/setup-gradle@v4
            
          - name: Build with Gradle
            working-directory: ./app
            run: ./gradlew build

          - name: SonarQube Scan
            uses: SonarSource/sonarqube-scan-action@v5.3.0 # Ex: v4.1.0, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
            with:
              projectBaseDir: app/src
            env: 
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 

