name: Java CI Action
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Setup Java JDK
            uses: actions/setup-java@v4.7.1
            with:
              java-version: '21'
              distribution: 'temurin'

          - name: Grant execute permission for gradlew
            run: chmod +x ./app/gradlew

          - name: Run tests with Gradle
            working-directory: ./app
            run: ./gradlew test

          - name: JaCoCo coverage report
            working-directory: ./app
            run: ./gradlew jacocoTestReport
  
          # uploads the coverage-report.md artifact
          - name: Upload Code Coverage Artifacts
            uses: actions/upload-artifact@v4
            with:
              name: code-coverage-report-markdown
              path: app/build/reports/jacoco/test/html
              retention-days: 1  

          - name: Cache SonarQube packages
            uses: actions/cache@v4
            with:
              path: ~/.sonar/cache
              key: ${{ runner.os }}-sonar
              restore-keys: ${{ runner.os }}-sonar
          - name: Cache Gradle packages
            uses: actions/cache@v4
            with:
              path: ~/.gradle/caches
              key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
              restore-keys: ${{ runner.os }}-gradle
          - name: Build and analyze
            env:
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            working-directory: ./app
            run: ./gradlew build sonar --info

